"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-08-09 16:44:53.324031
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Alembic renders custom column types with their full module path but does not
# add the import for them.
import app.db.types


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('einstellung',
    sa.Column('schluessel', sa.String(), nullable=False),
    sa.Column('wert', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('schluessel', name=op.f('pk_einstellung'))
    )
    op.create_table('notenschluessel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bezeichnung', sa.String(), nullable=False),
    sa.Column('typ', sa.String(), nullable=False),
    sa.Column('schwellen', sa.JSON(), nullable=False),
    sa.Column('ist_platzhalter', sa.Boolean(), nullable=False),
    sa.CheckConstraint("typ IN ('ihk', 'rlp_standard', 'benutzerdefiniert')", name=op.f('ck_notenschluessel_typ_gueltig')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notenschluessel')),
    sa.UniqueConstraint('bezeichnung', name=op.f('uq_notenschluessel_bezeichnung'))
    )
    op.create_table('schuljahr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bezeichnung', sa.String(), nullable=False),
    sa.Column('beginn', sa.Date(), nullable=False),
    sa.Column('ende', sa.Date(), nullable=False),
    sa.Column('ist_aktiv', sa.Boolean(), nullable=False),
    sa.CheckConstraint('ende > beginn', name=op.f('ck_schuljahr_ende_nach_beginn')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schuljahr')),
    sa.UniqueConstraint('bezeichnung', name=op.f('uq_schuljahr_bezeichnung'))
    )
    op.create_table('halbjahr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schuljahr_id', sa.Integer(), nullable=False),
    sa.Column('nummer', sa.Integer(), nullable=False),
    sa.Column('beginn', sa.Date(), nullable=False),
    sa.Column('ende', sa.Date(), nullable=False),
    sa.CheckConstraint('ende > beginn', name=op.f('ck_halbjahr_ende_nach_beginn')),
    sa.CheckConstraint('nummer IN (1, 2)', name=op.f('ck_halbjahr_nummer_gueltig')),
    sa.ForeignKeyConstraint(['schuljahr_id'], ['schuljahr.id'], name=op.f('fk_halbjahr_schuljahr_id_schuljahr'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_halbjahr')),
    sa.UniqueConstraint('schuljahr_id', 'nummer', name=op.f('uq_halbjahr_schuljahr_id_nummer'))
    )
    op.create_table('klasse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schuljahr_id', sa.Integer(), nullable=False),
    sa.Column('bezeichnung', sa.String(), nullable=False),
    sa.Column('notiz', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['schuljahr_id'], ['schuljahr.id'], name=op.f('fk_klasse_schuljahr_id_schuljahr'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_klasse')),
    sa.UniqueConstraint('schuljahr_id', 'bezeichnung', name=op.f('uq_klasse_schuljahr_id_bezeichnung'))
    )
    op.create_table('kurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('klasse_id', sa.Integer(), nullable=False),
    sa.Column('fach', sa.String(), nullable=False),
    sa.Column('notenschluessel_id', sa.Integer(), nullable=True),
    sa.Column('notiz', sa.Text(), nullable=True),
    sa.Column('gewicht_halbjahr_1', app.db.types.DecimalText(), nullable=True),
    sa.Column('gewicht_halbjahr_2', app.db.types.DecimalText(), nullable=True),
    sa.CheckConstraint('(gewicht_halbjahr_1 IS NULL) = (gewicht_halbjahr_2 IS NULL)', name=op.f('ck_kurs_halbjahrgewichte_paarweise')),
    sa.ForeignKeyConstraint(['klasse_id'], ['klasse.id'], name=op.f('fk_kurs_klasse_id_klasse'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notenschluessel_id'], ['notenschluessel.id'], name=op.f('fk_kurs_notenschluessel_id_notenschluessel'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kurs')),
    sa.UniqueConstraint('klasse_id', 'fach', name=op.f('uq_kurs_klasse_id_fach'))
    )
    op.create_table('schueler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vorname', sa.String(), nullable=False),
    sa.Column('nachname', sa.String(), nullable=False),
    sa.Column('klasse_id', sa.Integer(), nullable=False),
    sa.Column('listennummer', sa.Integer(), nullable=True),
    sa.Column('foto', sa.LargeBinary(), nullable=True),
    sa.Column('foto_geaendert_am', sa.DateTime(), nullable=True),
    sa.Column('notiz', sa.Text(), nullable=True),
    sa.Column('ist_aktiv', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['klasse_id'], ['klasse.id'], name=op.f('fk_schueler_klasse_id_klasse'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schueler'))
    )
    op.create_table('kursteilnahme',
    sa.Column('kurs_id', sa.Integer(), nullable=False),
    sa.Column('schueler_id', sa.Integer(), nullable=False),
    sa.Column('ist_aktiv', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['kurs_id'], ['kurs.id'], name=op.f('fk_kursteilnahme_kurs_id_kurs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schueler_id'], ['schueler.id'], name=op.f('fk_kursteilnahme_schueler_id_schueler'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('kurs_id', 'schueler_id', name=op.f('pk_kursteilnahme'))
    )
    op.create_table('notengruppe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kurs_id', sa.Integer(), nullable=False),
    sa.Column('halbjahr_id', sa.Integer(), nullable=False),
    sa.Column('bezeichnung', sa.String(), nullable=False),
    sa.Column('gewicht', app.db.types.DecimalText(), nullable=False),
    sa.Column('reihenfolge', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['halbjahr_id'], ['halbjahr.id'], name=op.f('fk_notengruppe_halbjahr_id_halbjahr'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kurs_id'], ['kurs.id'], name=op.f('fk_notengruppe_kurs_id_kurs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notengruppe')),
    sa.UniqueConstraint('kurs_id', 'halbjahr_id', 'bezeichnung', name=op.f('uq_notengruppe_kurs_id_halbjahr_id_bezeichnung'))
    )
    op.create_table('notenueberschreibung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schueler_id', sa.Integer(), nullable=False),
    sa.Column('kurs_id', sa.Integer(), nullable=False),
    sa.Column('bezugszeitraum', sa.String(), nullable=False),
    sa.Column('notenwert', app.db.types.DecimalText(), nullable=False),
    sa.Column('quelle', sa.String(), nullable=False),
    sa.Column('begruendung', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=False),
    sa.CheckConstraint("bezugszeitraum IN ('halbjahr_1', 'halbjahr_2', 'jahr')", name=op.f('ck_notenueberschreibung_bezugszeitraum_gueltig')),
    sa.CheckConstraint("quelle IN ('berechnet_uebernommen', 'manuell')", name=op.f('ck_notenueberschreibung_quelle_gueltig')),
    sa.ForeignKeyConstraint(['kurs_id'], ['kurs.id'], name=op.f('fk_notenueberschreibung_kurs_id_kurs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schueler_id'], ['schueler.id'], name=op.f('fk_notenueberschreibung_schueler_id_schueler'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notenueberschreibung'))
    )
    op.create_table('leistung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notengruppe_id', sa.Integer(), nullable=False),
    sa.Column('bezeichnung', sa.String(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('notenschluessel_id', sa.Integer(), nullable=True),
    sa.Column('max_punkte', app.db.types.DecimalText(), nullable=True),
    sa.Column('gewicht', app.db.types.DecimalText(), nullable=False),
    sa.Column('notiz', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['notengruppe_id'], ['notengruppe.id'], name=op.f('fk_leistung_notengruppe_id_notengruppe'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notenschluessel_id'], ['notenschluessel.id'], name=op.f('fk_leistung_notenschluessel_id_notenschluessel'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leistung'))
    )
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leistung_id', sa.Integer(), nullable=False),
    sa.Column('schueler_id', sa.Integer(), nullable=False),
    sa.Column('eingabeart', sa.String(), nullable=False),
    sa.Column('punkte', app.db.types.DecimalText(), nullable=True),
    sa.Column('notenwert', app.db.types.DecimalText(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notiz', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(), nullable=False),
    sa.CheckConstraint("eingabeart <> 'note' OR punkte IS NULL", name=op.f('ck_note_keine_punkte_bei_noteneingabe')),
    sa.CheckConstraint("eingabeart <> 'punkte' OR punkte IS NOT NULL", name=op.f('ck_note_punkte_bei_punkteingabe')),
    sa.CheckConstraint("eingabeart IN ('note', 'punkte')", name=op.f('ck_note_eingabeart_gueltig')),
    sa.CheckConstraint("status <> 'gewertet' OR notenwert IS NOT NULL", name=op.f('ck_note_notenwert_bei_gewertet')),
    sa.CheckConstraint("status IN ('gewertet', 'nicht_gewertet', 'nicht_erbracht')", name=op.f('ck_note_status_gueltig')),
    sa.ForeignKeyConstraint(['leistung_id'], ['leistung.id'], name=op.f('fk_note_leistung_id_leistung'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schueler_id'], ['schueler.id'], name=op.f('fk_note_schueler_id_schueler'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_note')),
    sa.UniqueConstraint('leistung_id', 'schueler_id', name=op.f('uq_note_leistung_id_schueler_id'))
    )
    op.create_table('note_historie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('schueler_id', sa.Integer(), nullable=False),
    sa.Column('leistung_id', sa.Integer(), nullable=False),
    sa.Column('aktion', sa.String(), nullable=False),
    sa.Column('alter_notenwert', app.db.types.DecimalText(), nullable=True),
    sa.Column('alter_status', sa.String(), nullable=True),
    sa.Column('neuer_notenwert', app.db.types.DecimalText(), nullable=True),
    sa.Column('neuer_status', sa.String(), nullable=True),
    sa.Column('zeitpunkt', sa.DateTime(), nullable=False),
    sa.CheckConstraint("aktion IN ('angelegt', 'geaendert', 'geloescht')", name=op.f('ck_note_historie_aktion_gueltig')),
    sa.CheckConstraint("alter_status IS NULL OR alter_status IN ('gewertet', 'nicht_gewertet', 'nicht_erbracht')", name=op.f('ck_note_historie_alter_status_gueltig')),
    sa.CheckConstraint("neuer_status IS NULL OR neuer_status IN ('gewertet', 'nicht_gewertet', 'nicht_erbracht')", name=op.f('ck_note_historie_neuer_status_gueltig')),
    sa.ForeignKeyConstraint(['leistung_id'], ['leistung.id'], name=op.f('fk_note_historie_leistung_id_leistung'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schueler_id'], ['schueler.id'], name=op.f('fk_note_historie_schueler_id_schueler'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_note_historie'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note_historie')
    op.drop_table('note')
    op.drop_table('leistung')
    op.drop_table('notenueberschreibung')
    op.drop_table('notengruppe')
    op.drop_table('kursteilnahme')
    op.drop_table('schueler')
    op.drop_table('kurs')
    op.drop_table('klasse')
    op.drop_table('halbjahr')
    op.drop_table('schuljahr')
    op.drop_table('notenschluessel')
    op.drop_table('einstellung')
    # ### end Alembic commands ###
