"""sitzplan (specification 5.6)

Two new tables, nothing else: no existing row is read, changed or moved. A
class gets its ``sitzplan`` row when the plan is opened for the first time,
so this migration leaves every class without one.

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-19 12:33:18.776375
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Alembic renders custom column types with their full module path but does not
# add the import for them. Keeping it here means an autogenerated migration
# that touches a DecimalText column is runnable as generated, instead of
# failing with a NameError against the productive database.
import app.db.types


revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sitzplan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('klasse_id', sa.Integer(), nullable=False),
    sa.Column('reihen', sa.Integer(), nullable=False),
    sa.Column('sitze_je_reihe', sa.Integer(), nullable=False),
    sa.CheckConstraint('reihen BETWEEN 1 AND 12', name=op.f('ck_sitzplan_reihen_gueltig')),
    sa.CheckConstraint('sitze_je_reihe BETWEEN 1 AND 12', name=op.f('ck_sitzplan_sitze_je_reihe_gueltig')),
    sa.ForeignKeyConstraint(['klasse_id'], ['klasse.id'], name=op.f('fk_sitzplan_klasse_id_klasse'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sitzplan')),
    sa.UniqueConstraint('klasse_id', name=op.f('uq_sitzplan_klasse_id'))
    )
    op.create_table('sitzplatz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sitzplan_id', sa.Integer(), nullable=False),
    sa.Column('schueler_id', sa.Integer(), nullable=False),
    sa.Column('reihe', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.CheckConstraint('position >= 1', name=op.f('ck_sitzplatz_position_gueltig')),
    sa.CheckConstraint('reihe >= 1', name=op.f('ck_sitzplatz_reihe_gueltig')),
    sa.ForeignKeyConstraint(['schueler_id'], ['schueler.id'], name=op.f('fk_sitzplatz_schueler_id_schueler'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sitzplan_id'], ['sitzplan.id'], name=op.f('fk_sitzplatz_sitzplan_id_sitzplan'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sitzplatz')),
    sa.UniqueConstraint('sitzplan_id', 'reihe', 'position', name=op.f('uq_sitzplatz_sitzplan_id_reihe_position')),
    sa.UniqueConstraint('sitzplan_id', 'schueler_id', name=op.f('uq_sitzplatz_sitzplan_id_schueler_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sitzplatz')
    op.drop_table('sitzplan')
    # ### end Alembic commands ###
