"""arbeitet_digital (specification 3.1)

One column on ``schueler``: whether the pupil works on a device of their own.
Display only -- 3.1 rules out any effect on the calculation, the export or the
course enrolment.

``server_default`` is not decoration. SQLite cannot add a NOT NULL column to a
table that already holds rows without one; batch mode rebuilds the table and
the copying step would have nothing to write. Every existing pupil therefore
starts at false, which is the intended default anyway: too many paper copies
costs paper, too few costs a lesson.

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-26 13:12:32.673943
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Alembic renders custom column types with their full module path but does not
# add the import for them. Keeping it here means an autogenerated migration
# that touches a DecimalText column is runnable as generated, instead of
# failing with a NameError against the productive database.
import app.db.types


revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schueler', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'arbeitet_digital',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schueler', schema=None) as batch_op:
        batch_op.drop_column('arbeitet_digital')

    # ### end Alembic commands ###
